title: James Hanlon
email: your-email@example.com
description: >-
  Professional website of James Hanlon. Sharing knowledge, insights, and projects.

baseurl: ""  # Leave blank unless using a subpath
url: "https://jameshanlon1.github.io/"  # Your site URL

twitter_username: jameshanlon
github_username: jameshanlon1

# **Use Alembic Theme**
theme: alembic-jekyll-theme


# **Required plugins for GitHub Pages**
plugins:
  - jekyll-remote-theme  # 🚀 THIS IS REQUIRED FOR GITHUB TO LOAD THE THEME!
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# **Ensure GitHub Pages processes these files**
include: ["_pages"]

# **Exclude unnecessary files**
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
